### ISSUE TITLE
Build fails on Mac OS/X Sierra

### ISSUE THREAD

**Issue by cypromis** [01org/isa-l#11]
In file included from igzip/igzip_stateless_base.c:3:
igzip/huffman.h:144:9: error: always_inline function '_mm_crc32_u32' requires target feature 'sse4.2', but would be
      inlined into function 'compute_hash' that is compiled without support for 'sse4.2'
        return _mm_crc32_u32(0, data);
               ^
1 error generated.

**Comment by gbtucker** [comment]
OK, thanks I see the issue.  I'll have a fix out soon.

**Comment by cypromis** [comment]
Any update on this ?

**Comment by gbtucker** [comment]
Sorry for the delay. This got caught up in a bundle of compression improvements we are testing together and will push shortly.

**Comment by cypromis** [comment]
Thanks for the update :)

**Comment by gbtucker** [comment]
@cypromis can you retest with the latest? It should be fixed now.

**Comment by cypromis** [comment]
Seems to work with ./configure --target=darwin.

**Comment by cypromis** [comment]
Will you create a 2.17.0 release now so I can change my build scripts for packages ?
:)

**Comment by gbtucker** [comment]
@cypromis Tagged v2.17.0.
