### ISSUE TITLE
Error when running "make" on Ubuntu 16.04

### ISSUE THREAD

**Issue by lespaulgt** [01org/isa-l#14]
With a prior install of NASM, I'm getting an error when running "make". Any input on this?

devops@controller:~/ISA-L/isa-l$ make
make --no-print-directory all-am
  MKTMP    erasure_code/gf_vect_mul_sse.s
  CCAS     erasure_code/gf_vect_mul_sse.lo
erasure_code/gf_vect_mul_sse.s:119: warning: absolute address can not be RIP-relative
erasure_code/gf_vect_mul_sse.s:161: warning: label `endproc_frame' defined on pass two
erasure_code/gf_vect_mul_sse.s:170: warning: label `slversion' defined on pass two
erasure_code/gf_vect_mul_sse.s:170: error: parser: instruction expected
Makefile:2367: recipe for target 'erasure_code/gf_vect_mul_sse.lo' failed
make[1]: *** [erasure_code/gf_vect_mul_sse.lo] Error 1
rm erasure_code/gf_vect_mul_sse.s
Makefile:1496: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gbtucker** [comment]
What version of nasm are you using?

**Comment by lespaulgt** [comment]
Issue has been resolved. I had to reinstall nasm using apt-get. For some reason it was not installing properly when cloned from the repo.
