### ISSUE TITLE
Loops improve erasure_code_encode_cold perf test (old title: xor can use VPXOR to improve peformance)

### ISSUE THREAD

**Issue by templexxx** [01org/isa-l#17]
I found that isa-l's xor only have avx version. Why not use vpxor?  And I heard (V)PXOR can run on any of the 3 ALU execution ports, p0/p1/p5.  (V)XORPS/D can only run on p5.  Is it right?

**Comment by templexxx** [comment]
I write a xor engine in Golang(use vpxor),  and my version is more than 15G.  isa-l only 13G.  they both run on a linux vm on my macbook

**Comment by gbtucker** [comment]
As in #18 I think much of the performance difference may be due to test issues and you may notice that xor_gen_perf may vary by over 3x between cold and warm options.  Exchanging vpxor and vxorps probably won't make much difference on modern hardware.  You may notice on other functions that they are interleaved intentionally but this is an optimization for older hardware and shouldn't help or hinder on a modern CPU.

**Comment by templexxx** [comment]
@gbtucker  Thank you for your help!

Sorry for late. I spent more time on test the performance. I tried to understand what you said here. You mention the warm and cold options, "warm" can get more CPU cache's power, so it is faster. Am I right?

I make some test  on cold options. For example, I recorded the "erasure_code_encode_cold"'s performance, after several times test, I found a question that I can't figure it out. 

Here is my test steps:
1. I set the "TEST_LEN(m)" 128 *1024*1024 in the "erasure_code_perf.c"  under "uncached test"
2. And m=14, k=10.  
3. I use 1, 10, 30 as the LOOPS
*** I use k*test_len/cost as the performance result ( ISA-L use m*test_len)
*** run on a CPU which support avx2

TEST Result:
LOOP1        588MB/S
LOOP10     31118MB/S
LOOP30    3703MB/S

The performance will improve if I set the LOOPS bigger. But I think the data size is big enough( much bigger than L3 cache size), how could it benefit by CPU cache?

If the improvement is not caused by CPU cache, what is that make test faster? 
Maybe the question is not just about the erasure code.
It will happened in memory copy test too.

I teach program myself, so maybe I miss some important things about this?

**Comment by templexxx** [comment]
And I found VMOVDQA and VMOVDQU are both in your codes.   I read this article [http://lemire.me/blog/2012/05/31/data-alignment-for-speed-myth-or-reality/](url), it said unaligned is not a big deal for modern CPU. But in intel optimization reference manual(June 2016) said aligned is important in performance. VMOVDQA are used to move input/output data in your codes,  so I think align is the better choice?

**Comment by templexxx** [comment]
Just now, I change all VMOVDQA to VMOVDQU. After several test, the erasure_code_encode_cold's speed is almost same. I can't see the difference.

**Comment by templexxx** [comment]
Maybe it's store buffer help to improve performance?  EC or memory copy in a loop will always operate two same memory address(one for read, one for output).  So maybe it's store buffer to reduce the times of really write(write to memory)?

**Comment by templexxx** [comment]
And I found if I unroll loops, it will improve performance a little.

My test steps:
1. one loop calculate 32 bytes, I "repeat" it 8 times, so it calculate 256bytes per loop
2. use more register, but part of them keep same:
mask, low_table, high_table, src & dest address's register  are same in every 8 times
3. repeat 8 times will give me the best performance. If it's just 2, it will improve not much. if it's 16, there is no difference with 8
4. encode 10+4 (16MB per shards) on a i5-4278U. the output is 4300-4400MB/s if 32bytes per loop. But if I calc 256bytes per loop, it will be 4500-4600MB/s. (encode task will run 50 times, and the the avg speed will be the result)

Here is my question:
1. the improve is due to loops unroll or cpu pipeline? Or both of them?
2. I read a book about assembly written by Daniel Kusswurm, it said a cpu core has 8 ports. This give us chance to do some calculation in parallel. And It also said we should reduce the register dependent, does it means I should reduce register reusing for parallel? That's why I try to unroll loops, and it really help

**Comment by templexxx** [comment]
I made a mistake, isa-l's xor is super fast. Thank you for your contribution, it's so cool
