### ISSUE TITLE
Don't we need "SFENCE" for Non-Temporal Hint?

### ISSUE THREAD

**Issue by templexxx** [01org/isa-l#22]
For example:

in raid/xor_gen_avx.asm   line 93:

 %define XSTR vmovntdq

don't we need to put a "sfence"  in front of RET?

**Comment by gbtucker** [comment]
Technically yes, you do need a fence before doing a read on parity written with NT store instructions.  You can do this at any time after calling a series xor_gen().

**Comment by templexxx** [comment]
@gbtucker 

Thank you! 

You really helped me a lot
