### ISSUE TITLE
Clarify gf_gen_rs_matrix documentation

### ISSUE THREAD

**Issue by asomers** [01org/isa-l#26]
In the PDF documentation for `gf_gen_rs_matrix`, there is a list of inequalities which will guarantee that every submatrix of the result will be invertible.  However, the inequalities are rendered in such a way that they all kind of run together.  Maybe there are some missing commas?  Or maybe the inequalities come in pairs?  It's really unclear.  Could you please clarify it?

**Comment by gbtucker** [comment]
There is a test function included called gen_rs_matrix_limits that is intended to help explore the bounties where sub-matrices are invertible for gf_gen_rs_matrix up to some max.  It should make it more clear as it prints for each k the highest m found up to max search.  Note that the encoding generator functions gf_gen_rs_matrix() and gf_gen_cauchy1_matrix() are only two examples of how to pick an encoder and the function ec_encode_data() will work for any encoding matrix.

**Comment by gbtucker** [comment]
Sorry, I realize what you mean now about the pdf version.  Doxygen was collapsing newlines and running them together.  We pushed a fix in latest.
