### ISSUE TITLE
lrc support

### ISSUE THREAD

**Issue by bigfreeZhou** [01org/isa-l#28]
do we have plan to support lrc erasure codes?

**Comment by gbtucker** [comment]
We already can support lrc erasure codes.  Lrc codes are just a different encoding matrix that are more sparse than a typical code.  ISA-L ec can do any encoding matrix.  An lrc (4, 4, 1) encode matrix, 4 sources, 4 local parity, 1 global parity, may look like:
` 1  0  0  0`
` 0  1  0  0`
` 0  0  1  0`
` 0  0  0  1`
` a  b  0  0`  (local parity 1)
` c  d  0  0`  (local parity 2)
` 0  0  e  f`  (local parity 3)
` 0  0  g  h` (local parity 4)
`  i  j  k  l`   (global parity)

You could perform the encode more efficiently by breaking up into three pieces:
(p1, p2) = f(s1, s2);
(p3, p4) = f(s3, s4); 
p5 = f(s1, s2, s3, s4);

**Comment by templexxx** [comment]
@bigfreeZhou by the way you must be sure any sub-matrix can make a inverse matrix (for global parity's encoding matrix)

**Comment by xiangcai1215** [comment]
can i

**Comment by xiangcai1215** [comment]
where can I see the example of using LRC

**Comment by gbtucker** [comment]
@xiangcai1215 We don't have a specific example of an LRC code but it would be fairly easy to change the encoding matrix in the existing examples to something with some sparsity for local parity.  There are lots of choices for coefficients and in a real implementation you would also have to map individual erasures to required src/parity combinations unlike the existing examples of just pick any k.

**Comment by xiangcai1215** [comment]
for example，LRC（4,4,1）,4 sources, 4 local parity, 1 global parity。
How can we get the **encoding matrix** to calculate global parity and local parity at once?
If we can use the function：void gf_gen_cauchy1_matrix(unsigned char *a, int m, int k)  to get the encoding matrix?

**Comment by gbtucker** [comment]
I guess you could use gf_gen_cauchy1_matrix(a, 9, 4) and then zero the non-local coefficients as above but I'm not sure this is the best choice or what the ramifications are for recovery cases.

**Comment by GitXn** [comment]
This lrc-matrix construction method is only valid when global block count is 1.
what if global block count > 1? how to construct a matrix satisfying MR(maximum recoverable) using isa-l?

**Comment by GitXn** [comment]
When the number of global blocks is greater than 5, there is no way to violently enumerate to get a suitable matrix. 
Is there a better construction scheme compared to filling zeros with the Cauchy matrix?
