### ISSUE TITLE
NASM Compile Error: invalid combination of opcode and operands

### ISSUE THREAD

**Issue by amaier17** [01org/isa-l#29]
Getting the following errors with the latest builds on nasm v2.11.08 :
igzip/igzip_gen_icf_map_lh1_06.s:284: error: invalid combination of opcode and operands
igzip/igzip_gen_icf_map_lh1_06.s:371: error: invalid combination of opcode and operands

**Comment by gbtucker** [comment]
Thanks,
Testing a fix now.  Looks like you will need to upgrade to nasm 2.13 to get
AVX512 due to a nasm bug.  I'll test for the offending instruction in
config and fall back to no AVX512 if you have 2.11.

**Comment by gbtucker** [comment]
@amaier17 can you check out the latest?

**Comment by amaier17** [comment]
@gbtucker Yup that fixed the compile with nasm 2.11. Thanks!
