### ISSUE TITLE
sizeof(void *)may cause problem

### ISSUE THREAD

**Issue by young66** [01org/isa-l#33]
the deflate_hdr has type of (uin8_t *)
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1473
the following line use sizeof(uin8_t *) may cause problem
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1515
same problem in 
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/huff_codes.c#L1422

**Comment by rjoursler** [comment]
Thank you for submitting this issue, we will go ahead and fix it.
