### ISSUE TITLE
code_list[0] Uninitialized may cause  illegal memory accesses

### ISSUE THREAD

**Issue by young66** [01org/isa-l#35]
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L243

https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L403

**Comment by rjoursler** [comment]
Thank you for submitting this issue, but code_list[0] is always initialized. The loop

https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L230-L237

sorts the elements of huff_code_table by reference. As such code_list[0] is set in every case but when there are no elements to sort. The if statement just before this loop

https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L225-L228

handles the case when no elements are present.

**Comment by youngchopin** [comment]
FYI
in my Code Quality tool show a High impact, the work flow is the step 1 to step 15
`1. var_decl: Declaring variable code_list without initializer.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L211
`2. Condition i < 17, taking true branch.`
`4. Condition i < 17, taking true branch.`
`6. Condition i < 17, taking false branch.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L221
`3. Jumping back to the beginning of the loop.`  
`5. Jumping back to the beginning of the loop.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L222-L224
`7. Condition code_list_len == 0, taking false branch.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L225-L228
`8. Condition i < table_length, taking true branch.`  
`11. Condition i < table_length, taking false branch.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L229-L230
`9. Condition code_length > 0, taking false branch.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L231-L236
`10. Jumping back to the beginning of the loop.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L237-L239
`12. Condition i < 16 /* 15 + 1 */, taking true branch.`  
`14. Condition i < 16 /* 15 + 1 */, taking false branch.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L240
`13. Jumping back to the beginning of the loop.`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L241
`CID xxxxxxxx (#1 of 1): Uninitialized pointer read (UNINIT)`
`15. uninit_use: Using uninitialized value code_list[0].`
https://github.com/01org/isa-l/blob/9e79faeeff129ce5964fc40174d007c32e49e5b3/igzip/igzip_inflate.c#L243
