### ISSUE TITLE
compilation error:  ./tools/yasm-filter.sh: Permission denied

### ISSUE THREAD

**Issue by fomy** [01org/isa-l#37]
>   CC     igzip/igzip_inflate.lo
>   CC     erasure_code/ec_highlevel_func.lo
>   MKTMP    erasure_code/gf_vect_mul_sse.s
>   CCAS   erasure_code/gf_vect_mul_sse.lo
> ./libtool: line 1111: ./tools/yasm-filter.sh: Permission denied
> make[1]: *** [erasure_code/gf_vect_mul_sse.lo] Error 1
> rm erasure_code/gf_vect_mul_sse.s
> make: *** [all] Error 2

Does anyone know how to solve this problem?

Thanks

**Comment by gbtucker** [comment]
I haven't seen this problem before but as a permission issue perhaps a permission was changed or temp file created as root, etc.  I would suggest starting clean `make distclean; git clean -i -d` and see if `git show` shows any changes.

**Comment by fomy** [comment]
Maybe only the master has this problem.
I download isa-l-2.22.0 instead, and pass the compilation.

Thanks

**Comment by gbtucker** [comment]
Thanks, closing the issue.  Please let us know if you can see the issue again.
