### ISSUE TITLE
find a bug : code can not support specific case  

### ISSUE THREAD

**Issue by liuiangang** [01org/isa-l#40]
if k=9,m=18, and column in (0, 1, 2, 5, 7, 9, 10, 14, 16) corrupt, isa cannot decode 
when execute example, report as follows:
erasure_code_test: 127x8192 BAD MATRIX
Fail to gf_gen_decode_matrix

**Comment by liuiangang** [comment]
![p a360n 7k2jwmu zmunmc](https://user-images.githubusercontent.com/12525667/42619323-4fedea32-85ea-11e8-9366-24f59f6613f8.png)
![v h3wia8s w yvuh9x 8a](https://user-images.githubusercontent.com/12525667/42619346-64b5f45a-85ea-11e8-9b42-200b84543775.png)

![p m3tlm 9 2k6o0 51v_286](https://user-images.githubusercontent.com/12525667/42619363-6fcbb3c0-85ea-11e8-92da-939c2aabecdd.png)

**Comment by gbtucker** [comment]
I don't think this is a bug but you are pushing the limits of a Vandermonde matrix.  As described in the header for [gf_gen_rs_matrix](https://github.com/01org/isa-l/blob/master/include/erasure_code.h#L884) for k =  9 you are not guaranteed an invertable matrix unless m <= 13.  You might consider using a different encoding matrix like a Cauchy-based one the example uses.  You can test this will work with:
````
$ ./ec_simple_example -k 9 -p 9 -e 0 -e 1 -e 2 -e 5 -e 7 -e 9 -e 10 -e 14 -e 16
ec_simple_example:
 encode (m,k,p)=(18,9,9) len=8192
 recover 9 fragments
 check recovery of block { 0 1 2 5 7 9 10 14 16 } done all: Pass
````

**Comment by liuiangang** [comment]
Thanks，yesterday I use Cauchy-based matrix， it does work
