### ISSUE TITLE
crc32_iscsi_01 touches memory when the buffer length is zero

### ISSUE THREAD

**Issue by shelepov** [01org/isa-l#43]
crc32_iscsi_01.asm, line 408: mov rbx, qword [bufptmp]

When the buffer length is zero (and the buffer address is 64-bit aligned), the above line reads a qword at the buffer address, which is technically reading past the end of the buffer. In particular, calling the function with (NULL, 0, crc) results in a segfault.

**Comment by gbtucker** [comment]
Thanks for reporting @shelepov. I think we can fix by moving the short len test to before the align test. I'll give it a try and let you know.

**Comment by gbtucker** [comment]
Pushed a fix for this 105eeb967cc683e561791c60984591740b6e8dd7. Please give it a try @shelepov and let us know.

**Comment by shelepov** [comment]
Looks good.

**Comment by gbtucker** [comment]
Thanks for testing.
