### ISSUE TITLE
Failure to build on OSX using nasm

### ISSUE THREAD

**Issue by ehiggs** [01org/isa-l#47]
I found that building on OS X fails when using nasm due to `unknown symbol type: 'function'`. Using `yasm` instead appears to work.

**Comment by gbtucker** [comment]
Thanks for reporting.  It seems that nasm doesn't allow types on symbols when the output is macho64. We will look for a workaround on this.

**Comment by gbtucker** [comment]
I just pushed a fix for this now.  @ehiggs can you re-test on your setup?

**Comment by ehiggs** [comment]
@gbtucker I can successfully buidl using nasm now. Thanks for the quick response!

**Comment by gbtucker** [comment]
Thanks for testing @ehiggs. I'll close as fixed by 2e212f2.
