### ISSUE TITLE
Build configure err

### ISSUE THREAD

**Issue by caoli5288** [01org/isa-l#50]
Generated Makefile contains nasm -f elf64 when configure with --host=x86_64-w64-mingw32 on linux platform.

There are two questions. 
1. The format should be win64. 
2. Only yasm can be cross-compiled to win64.

**Comment by gbtucker** [comment]
Thanks for reporting.  I'm testing a fix that will force yasm on configure detecting mingw build.  In that case, as you noted, mingw will require yasm as nasm is missing a few features we currently use in the windows prelog.  I'll note when integrated.

**Comment by gbtucker** [comment]
The latest commit  32b5c41 should fix this so autodetected mingw will work with yasm and fail on an unsupported version.

**Comment by gbtucker** [comment]
This seems to be fixed so I'm going to close the issue.
