### ISSUE TITLE
Export Adler-32

### ISSUE THREAD

**Issue by zbjornson** [01org/isa-l#51]
It'd be nice to be able to use the fast Adler-32 implementations in this library. If you'd accept it, I'm happy to work on a PR if you provide some guidance on where you'd want it (a new `checksum.h`, `igzip_lib.h`, other). (Or if you'd rather do it yourself, also fine.)

Thank you!

(PS: I could see `checksum.h` being a useful starting point for adding [Intel's fast Fletcher checksums](https://software.intel.com/en-us/articles/fast-computation-of-fletcher-checksums) in the future also.)

**Comment by gbtucker** [comment]
Sounds fine to export isal_adler32().  Putting in `igzip_lib.h` will work.  Only other things you would want to do is change checksum32_funcs_test from unit_tests to check_tests in `igzip/Makefile.am` and add to `isa-l.def` list.  If we add Fletcher in the future we can see about breaking out then.
Thanks for the offer.  I'll look for your PR.

**Comment by gbtucker** [comment]
Closing issue as has been integrated.
