### ISSUE TITLE
crc16_t10dif_copy forward and reverse may be necessary if dst and src are overlapped.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [01org/isa-l#54]
Hi,

I'm developing DIF insertion and strip feature by stream fashion by using crc16_t10dif_copy in SPDK project.

The idea is that when we use sockets, incoming data can be split into multiple packets, and we read those packets sequentially into a data buffer. I want to insert DIF into the data buffer without using any bounce buffer. I also want to strip DIF from data buffer without any bounce buffer.

However when I use crc16_t10dif_copy, DIF insertion destroyed original data because src data is overwritten before calculating CRC. On the other hand, DIF strip worked.

So, I think that crc16_t10dif_copy_reverse will be necessary for DIF insertion and crc16_t10dif_copy_forward will be necessary for DIF strip.

Does ISA-L crc16_t10dif_copy cover such a overlapping case? I think if we emulate hardware behavior, we will have to cover such a overlapping case.

I will do workaround by using not crc_t10dif_copy but crc_t10dif + memmove for now. (we can't use memcpy because some tool complains about overlapping when we use memcpy.)

Any feedback is very appreciated.

Thanks,
Shuhei

**Comment by shuhei-matsumoto** [comment]
The following is related patches:

https://review.gerrithub.io/#/c/spdk/spdk/+/444831/
https://review.gerrithub.io/#/c/spdk/spdk/+/444840/

I hope they will be any help of you.

**Comment by jimharris** [comment]
Hi @shuhei-matsumoto,

Regarding "I also want to strip DIF from data buffer without any bounce buffer." - I think SPDK can do this without any ISA-L changes.  When iSCSI (or NVMe/TCP) transmits data, it can just construct an iov array to only point to the data portions of the buffer.  This will require some changes to iSCSI and NVMe/TCP to allocate and build these iov arrays.

Please let me know if you think this would work, or if there is still something you think SPDK needs from ISA-L in the strip path.

Thanks,

Jim

**Comment by jimharris** [comment]
I was just talking with @gbtucker - I wonder if we can first try something without ISA-L changes on the insert path.  For example - let's assume we have 4K iSCSI write payload.  Backing block device is configured with 512+8 block length.  So we need a data buffer of size 4K + (8 * 8) = 4160 bytes.

We use readv to read the data into the 4160 byte buffer such that it leaves 8 bytes of space after every 512 bytes of data.  Once we have all 4160 bytes, we just call the CRC routine (ISA-L if available, table driven implementation if not) 8 different times and write the CRC ourselves into the scattered 8 byte regions.

Talking with Greg, it's not likely we could get much (if any) improvement over this technique.  Most of the above we would need to implement anyways in SPDK - maybe we do that part first, do some benchmarking, and then follow back with Greg to see if the data matches expectations.

**Comment by shuhei-matsumoto** [comment]
Hi @jimharris @gbtucker 

Thanks you so much, that idea make sense to me and will be the best we can take now.

I think we will still need DIF strip and insertion when we create an I/O abstraction layer in the middle of SPDK I/O layer. But that will not require performance and crc16_t10dif + memcopy will be enough.

I close this issue and will re-open if I need any ISA-L change. it will take time until performance evaluation, but I will be able to share it with Greg through Jim.

Thanks again,
Shuhei
