### ISSUE TITLE
LARGE_WINDOW 32kb windows 

### ISSUE THREAD

**Issue by vlm** [01org/isa-l#9]
Hello!

I am configuring the project with `autogen.sh && ./configure CFLAGS=-DLARGE_WINDOW` to obtain 32kB deflate windows instead of default 8k. I am setting `.flush = SYNC_FLUSH` in the compression context after calling `isal_deflate_init()`.

The compression rate is virtually unchanged between 8k and 32k windows. The speed doesn't change at all. This prompts me to think about LARGE_WINDOW is not implemented properly, or the flag is not visible all the way through to the assembly code. However, I modified the `options.asm` manually to switch LARGE_WINDOW option on, and recompiled — to no avail. Here's my table on my large text data file I am using:

|  | Plain | ZLib (32kB) | ISA-L (8kB) | ISA-L (32kB) |
| --- | --- | --- | --- | --- |
| Compression rate | 1x | **5.68x** | 2.37x | 2.49x |

It is important to consider is that I am using a `.flush = SYNC_FLUSH` setting on blocks of about 5kB each at a time. Had it worked like `Z_FULL_FLUSH` (as in, discard the history window), it could lead to the observed behavior.

Would you please clarify whether this absense of a compression rate change is something I should expect after enabling `LARGE_WINDOW`.

**Comment by gbtucker** [comment]
Sync_flush does do what you expect and allow matches over submit bounties as does no_flush in statefull compress.  Changing the default to large_window may not have a big impact depending on data set unless you also change the default hufftables at compile time or use isal_create_hufftables() at runtime.

We are working on a number of improvements in compression that we will push soon that both improve the compression ratio and speed.  This includes making 32K window the default.

**Comment by vlm** [comment]
@gbtucker thanks.

Changing the default Huffman tables to the ones tailored to the data did increase compression ratio for 32kB windows from 2.49x to 3.97x.

But then, the same tables on 8kB windows gave 3.66x.

This prompts me to believe that larger windows are not getting using properly in this code.

**Comment by gbtucker** [comment]
It depends a lot on your data of course.  What data set are you using?

**Comment by vlm** [comment]
I created a demo script. It concatenates two random files of size ${BLOCK} and tries to compress them using `gzip -1` or ISA-L's `igzip_example` in 32-K mode.

```
[vlm@p1 igzip]$ ./test-compression.sh 8192
igzip_example
Window Size: 32 K
End of igzip_example

-rw-rw-r--. 1 vlm vlm 42311 Oct 26 02:02 outfile-gzip.bin
-rw-rw-r--. 1 vlm vlm 86845 Oct 26 02:02 outfile-isal-sync-flush.bin
[vlm@p1 igzip]$ ./test-compression.sh 8193
igzip_example
Window Size: 32 K
End of igzip_example

-rw-rw-r--. 1 vlm vlm  43302 Oct 26 02:02 outfile-gzip.bin
-rw-rw-r--. 1 vlm vlm 101067 Oct 26 02:02 outfile-isal-sync-flush.bin
[vlm@p1 igzip]$ ./test-compression.sh 8194
igzip_example
Window Size: 32 K
End of igzip_example

-rw-rw-r--. 1 vlm vlm  43500 Oct 26 02:02 outfile-gzip.bin
-rw-rw-r--. 1 vlm vlm 113796 Oct 26 02:02 outfile-isal-sync-flush.bin
[vlm@p1 igzip]$ 
```

As you see, the ISA-L breaks (performs much worse than `gzip -1`) pretty much all the time in SYNC_FLUSH mode.

## `test-compression.sh` file
```
#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <random_block_size>"
    exit
fi
BLOCK="$1"

# Use SYNC_FLUSH each BLOCK-sized block.
sed -i 's/NO_FLUSH/SYNC_FLUSH/' igzip_example.c

cc -I../include -DLARGE_WINDOW -o igzip_example igzip_example.c  -L ../.libs -lisal

# Two random blocks
dd if=/dev/urandom count=1 bs=${BLOCK} of=rnd1.bin 2>/dev/null
dd if=/dev/urandom count=1 bs=${BLOCK} of=rnd2.bin 2>/dev/null

# Create a large file out of repetition of two random blocks
rm -f infile.bin
for n in {1..100}; do
    cat rnd1.bin rnd2.bin >> infile.bin
done

cat infile.bin | gzip -1 > outfile-gzip.bin
./igzip_example infile.bin outfile-isal-sync-flush.bin

ls -al outfile-*.bin
```

**Comment by gbtucker** [comment]
I looked into this case and it's not that large_window or sync_flush isn't working.  The dataset is highly compressible with lots of large matches.  That the 16000 case compresses shows that large_window must be finding matches of distance > 8k even with sync_flush on.  After an initial set of literals there are mostly matches of max size 258.  At the end of an input segment when sync_flush is on the input must be drained resulting in a partial match of less than 258.  This results in a few more literals before max matches resume.  Since the compression ratio is so high on this dataset a few literals makes a big difference.  The other contributor is that when sync flush is on, a new header must be added at the start of each input block.  This contributes over 100 bytes every 8k.

**Comment by vlm** [comment]
What I see is that ISA-L does significantly (2 times) worse on my streaming data examples. I've prepared an apples-to-apples comparison code which executes `zlib` and `isal` in the same line-by-line mode (the line is about 1000 bytes long) and compare the output:

https://github.com/vlm/isa-l/commit/f77f252d3bb95659fbe7b97e82794e8eb418ba15

The scripts and the test file are in the above patch. The outcome:

```
./test-isal-vs-zlib.sh test.json

Observe:

-rw-rw-r--. 1 vlm vlm 121379 Oct 27 23:38 outfile-gzip-1.bin
-rw-rw-r--. 1 vlm vlm 278236 Oct 27 23:38 outfile-isal.bin
-rw-rw-r--. 1 vlm vlm 142806 Oct 27 23:38 outfile-zlib-1.bin
-rw-rw-r--. 1 vlm vlm 592008 Oct 27 23:36 test.json
```

Note that gzip-1 and zlib's deflate in a line-per-line mode yields about 4.1 .. 4.8x compression, whereas isa-l yields out about 2.1x compression under the same conditions.

**Comment by gbtucker** [comment]
It's true I didn't expect a common usage to be sync_flush so often on such small buffers.  Is sync_flush really necessary on every line?

Zlib probably puts a type 1, constant static block, for each line.  Without sync_flush on small buffers we do much better.
```
version 2.16:
$ ./igzip_file_perf test.json
  file test.json - in_size=592008 out_size=152714 iter=844 ratio_default=25.8% ratio_custom=21.8%
  igzip_file: runtime =     878183 usecs, bandwidth 476 MB in 0.8782 sec = 568.96 MB/s

prelim next release:
$ ./igzip_file_perf test.json
  file test.json - in_size=592008 out_size=140757 iter=844 ratio_default=23.8% ratio_custom=19.1%
  igzip_file: runtime =     614582 usecs, bandwidth 476 MB in 0.6146 sec = 813.00 MB/s
```
Would this make it worth it to delay the sync_flush in your usage?

**Comment by vlm** [comment]
The use case is streaming compression, such as WebSocket's [RFC 7692](https://tools.ietf.org/html/rfc7692). It requires a sync flush and mandates removing the terminating `00 00 ff ff` sequence for each message transmitted. My test replicates this behavior for typical data representative to whatever we see in the wild (the data is anonymized, but having similar entropy).

So, as much as we'd like the to avoid spontaneous flushing, this flushing has semantic significance and can't be avoided for this class of applications.

**Comment by gbtucker** [comment]
OK, perhaps there are some features we can add to help with the compression ratio in this case.

**Comment by vlm** [comment]
Any news on that or plans to address somehow?

**Comment by gbtucker** [comment]
Yes, we have pulled in the feature to do static (btype 01) headers.  This is the real issue on compression ratio with very small inputs and sync flush on.

**Comment by vlm** [comment]
Before the latest changes (i.e., copy from comment

```
./test-isal-vs-zlib.sh test.json

Observe:

-rw-rw-r--. 1 vlm vlm 121379 Oct 27 23:38 outfile-gzip-1.bin
-rw-rw-r--. 1 vlm vlm 278236 Oct 27 23:38 outfile-isal.bin
-rw-rw-r--. 1 vlm vlm 142806 Oct 27 23:38 outfile-zlib-1.bin
-rw-rw-r--. 1 vlm vlm 592008 Oct 27 23:36 test.json
```

After the latest changes:

```
./test-isal-vs-zlib.sh test.json

-rw-rw-r--. 1 vlm vlm 121379 Jan 11 06:03 outfile-gzip-1.bin
-rw-rw-r--. 1 vlm vlm 213130 Jan 11 06:03 outfile-isal.bin
-rw-rw-r--. 1 vlm vlm 142806 Jan 11 06:03 outfile-zlib-1.bin
```

From what I see, no tangible difference has been made on this type of load (278k->213k _ISA-L_ vs 142k _zlib_). ISA-L still gives 50% less efficient compression than Z_BEST_SPEED zlib.

All the sources are in https://github.com/vlm/isa-l/commit/12aa33a1f6cce53a0f7e6ac3b5744056a94cb722, just `./configure --disable-shared CFLAGS=-DLARGE_WINDOW`.

**Comment by gbtucker** [comment]
When you have such small blocks and sync flushing each one set for static hufftables.

isal_deflate_set_hufftables(stream, NULL, IGZIP_HUFFTABLE_STATIC);

**Comment by vlm** [comment]
With `isal_deflate_set_hufftables`:

```
New:
-rw-rw-r--. 1 vlm vlm 121379 Jan 12 22:17 outfile-gzip-1.bin
-rw-rw-r--. 1 vlm vlm 148602 Jan 12 22:17 outfile-isal.bin
-rw-rw-r--. 1 vlm vlm 142806 Jan 12 22:17 outfile-zlib-1.bin
-rw-rw-r--. 1 vlm vlm 592008 Jan 12 22:09 test.json
```

So, it is largely solved! Thank you very much!

**Comment by vlm** [comment]
However, there's another anomaly.

I tried to do the custom hufftables based on a 456k file. Now here's the result with DEFAULT hufftables, STATIC hufftables, and then a pair of `hufftables_default` and `hufftables_static` that were generated by the `generate_custom_hufftables` utility.

I would expect the custom hufftables to be markedly more efficient (in STATIC or DEFAULT) modes than the default ones shipped with igzip. However, they aren't:

| Uncompressed | DEFAULT | STATIC | "_default" CUSTOM | "_static" CUSTOM |
|---|---|---|---|---|
| 456k | 81k | 81k | *67k* | 81k | 

As you see, the custom hufftable in the DEFAULT mode works best, whereas in a STATIC mode the file outputs are exactly the same (81271 bytes!), irrespectively of whether the default (shipped) table is used or the generated one.

**Comment by gbtucker** [comment]
That's great.  I hope you see the point of isal_deflate_set_hufftables() is to give more control to the programmer especially when you know something about your data that you would rather not the compressor guess at.  As such setting IGZIP_HUFFTABLE_STATIC will force the use of btype 01 hufftables and header as specified by the standard.  If you changed the default hufftables this doesn't effect the format of the standard btype 01 static table so having the same compression ratio is expected.  The benefit being the 01 header is 100 bytes shorter.
For your use case I would suggest a decision is made based on the size of input.
```
if (length < 1024)  // or some threshold where a 100B header is worth it
     set to btype 01 hufftable
else
     set to custom hufftable
```
Then you can have the best of both worlds.

**Comment by vlm** [comment]
Thank you!
